name: Build

on:
  pull_request:
  push:
    branches:
      - master
      - '*'

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest]
        otp-version: [26, 27, 28]
    runs-on: ${{ matrix.platform }}
    container:
      image: erlang:${{ matrix.otp-version }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Compile
      run: make compile
    - name: EUnit Tests
      run: make eunit
    - name: Cover
      run: make cover
    - name: Elvis
      run: make elvis
    - name: Xref
      run: make xref
    - name: Hank
      run: make hank
    - name: Dialyzer
      run: make dialyzer
    - name: Check app calls
      run: make app_calls
    - name: Docs
      run: make doc
    - name: Formatter
      run: make format-verify
    - name: Publish Documentation
      uses: actions/upload-artifact@v4
      with:
        name: edoc OTP${{ matrix.otp-version }}
        path: doc
    - name: Upload Eunit Test result
      if: ${{ always() }}
      uses: actions/upload-artifact@v4
      with:
        name: Eunit test results ${{ matrix.otp-version }}
        path: .eunit/*.xml"
        retention-days: 7
